server:
  port: 8080
  servlet:
    context-path: /pothole

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test_authentication_app"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "tbaokiemcer@gmail.com"
    password: "kftnmntgbskpzwgs"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  clientKey: "1084624321365-ucd02hr6g8k2cotc1tbq5uugu7nt3bmh.apps.googleusercontent.com"
  using-time: 24
  signerKey: "d202aa63c931bf0b6b1722f897be3d54b3552c9362b5d9b3b5b539df329d4548"
  geocoding-api: "42e89a3c92f547efb51969b82f9ef4c2"


logging:
  level:
    root: INFO
    com:
      example: DEBUG
    org:
      springframework:
        security: DEBUG
        web:
          socket: DEBUG
        messaging: DEBUG
      hibernate: DEBUG